---
name: Publish site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to use actions/deploy-pages
      pages: write # to push to a github pages site
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo run --locked

      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist

      - id: deployment
        uses: actions/deploy-pages@v5
